version: '3.9'
   
services:
  db:
    image: postgres:12.11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=eventathon-db
      - POSTGRES_USER=eventathon-db
      - POSTGRES_PASSWORD=LocalDev123!
      - POSTGRES_HOST_AUTH_METHOD=md5
  app:
    build:
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

